[2024-06-26T08:01:28.677+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-26T08:01:29.051+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: update_allogistic.run_notebook scheduled__2024-06-26T07:00:00+00:00 [queued]>
[2024-06-26T08:01:29.208+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: update_allogistic.run_notebook scheduled__2024-06-26T07:00:00+00:00 [queued]>
[2024-06-26T08:01:29.387+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-26T08:01:29.942+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_notebook> on 2024-06-26 07:00:00+00:00
[2024-06-26T08:01:30.080+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=299) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-26T08:01:30.098+0000] {standard_task_runner.py:63} INFO - Started process 317 to run task
[2024-06-26T08:01:30.096+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'update_allogistic', 'run_notebook', 'scheduled__2024-06-26T07:00:00+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/allogistic.py', '--cfg-path', '/tmp/tmpf622l3gc']
[2024-06-26T08:01:30.116+0000] {standard_task_runner.py:91} INFO - Job 42: Subtask run_notebook
[2024-06-26T08:01:30.490+0000] {task_command.py:426} INFO - Running <TaskInstance: update_allogistic.run_notebook scheduled__2024-06-26T07:00:00+00:00 [running]> on host b92febf4feb2
[2024-06-26T08:01:31.167+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='update_allogistic' AIRFLOW_CTX_TASK_ID='run_notebook' AIRFLOW_CTX_EXECUTION_DATE='2024-06-26T07:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-26T07:00:00+00:00'
[2024-06-26T08:01:31.182+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-26T08:01:31.221+0000] {execute.py:83} INFO - Input Notebook:  /opt/***/dags/allogisticompiler.ipynb
[2024-06-26T08:01:31.224+0000] {execute.py:84} INFO - Output Notebook: /opt/***/dags/output_notebook.ipynb
[2024-06-26T08:01:32.018+0000] {logging_mixin.py:188} WARNING - Executing:   0%|          | 0/42 [00:00<?, ?cell/s]
[2024-06-26T08:01:33.122+0000] {kernelspec.py:284} WARNING - Kernelspec name python3 cannot be found!
[2024-06-26T08:01:33.124+0000] {manager.py:95} ERROR - No such kernel named python3
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/jupyter_client/manager.py", line 87, in wrapper
    out = await method(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jupyter_client/manager.py", line 435, in _async_start_kernel
    kernel_cmd, kw = await self._async_pre_start_kernel(**kw)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jupyter_client/manager.py", line 397, in _async_pre_start_kernel
    self.kernel_spec,
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jupyter_client/manager.py", line 195, in kernel_spec
    self._kernel_spec = self.kernel_spec_manager.get_kernel_spec(self.kernel_name)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jupyter_client/kernelspec.py", line 285, in get_kernel_spec
    raise NoSuchKernel(kernel_name)
jupyter_client.kernelspec.NoSuchKernel: No such kernel named python3
[2024-06-26T08:01:33.164+0000] {logging_mixin.py:188} WARNING - Executing:   0%|          | 0/42 [00:01<?, ?cell/s]
[2024-06-26T08:01:33.413+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-26T08:01:33.415+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/allogistic.py", line 33, in run_notebook
    pm.execute_notebook(
  File "/home/airflow/.local/lib/python3.12/site-packages/papermill/execute.py", line 116, in execute_notebook
    nb = papermill_engines.execute_notebook_with_engine(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/papermill/engines.py", line 48, in execute_notebook_with_engine
    return self.get_engine(engine_name).execute_notebook(nb, kernel_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/papermill/engines.py", line 370, in execute_notebook
    cls.execute_managed_notebook(nb_man, kernel_name, log_output=log_output, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/papermill/engines.py", line 442, in execute_managed_notebook
    return PapermillNotebookClient(nb_man, **final_kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/papermill/clientwrap.py", line 43, in execute
    with self.setup_kernel(**kwargs):
  File "/usr/local/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/nbclient/client.py", line 600, in setup_kernel
    self.start_new_kernel(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/nbclient/client.py", line 550, in async_start_new_kernel
    await ensure_async(self.km.start_kernel(extra_arguments=self.extra_arguments, **kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 198, in ensure_async
    result = await obj
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jupyter_client/manager.py", line 96, in wrapper
    raise e
  File "/home/airflow/.local/lib/python3.12/site-packages/jupyter_client/manager.py", line 87, in wrapper
    out = await method(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jupyter_client/manager.py", line 435, in _async_start_kernel
    kernel_cmd, kw = await self._async_pre_start_kernel(**kw)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jupyter_client/manager.py", line 397, in _async_pre_start_kernel
    self.kernel_spec,
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jupyter_client/manager.py", line 195, in kernel_spec
    self._kernel_spec = self.kernel_spec_manager.get_kernel_spec(self.kernel_name)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jupyter_client/kernelspec.py", line 285, in get_kernel_spec
    raise NoSuchKernel(kernel_name)
jupyter_client.kernelspec.NoSuchKernel: No such kernel named python3
[2024-06-26T08:01:33.511+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=update_allogistic, task_id=run_notebook, run_id=scheduled__2024-06-26T07:00:00+00:00, execution_date=20240626T070000, start_date=20240626T080129, end_date=20240626T080133
[2024-06-26T08:01:33.661+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 42 for task run_notebook (No such kernel named python3; 317)
[2024-06-26T08:01:33.747+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-26T08:01:34.094+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
