[2024-06-26T06:05:44.038+0000] {processor.py:161} INFO - Started process (PID=76) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T06:05:44.044+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T06:05:44.063+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:05:44.060+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T06:05:44.349+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:05:44.248+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T06:05:44.360+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T06:05:46.156+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 2.169 seconds
[2024-06-26T06:06:46.059+0000] {processor.py:161} INFO - Started process (PID=143) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T06:06:46.074+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T06:06:46.085+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:06:46.081+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T06:06:46.187+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:06:46.167+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T06:06:46.192+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T06:06:46.276+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.287 seconds
[2024-06-26T06:07:24.103+0000] {processor.py:161} INFO - Started process (PID=166) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T06:07:24.120+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T06:07:24.152+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:07:24.141+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T06:07:25.963+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:07:25.627+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T06:07:25.972+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T06:07:26.489+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 2.422 seconds
[2024-06-26T06:08:30.431+0000] {processor.py:161} INFO - Started process (PID=223) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T06:08:30.446+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T06:08:30.467+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:08:30.466+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T06:08:30.786+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:08:30.643+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T06:08:30.808+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T06:08:31.190+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.847 seconds
[2024-06-26T06:21:14.182+0000] {processor.py:161} INFO - Started process (PID=68) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T06:21:14.205+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T06:21:14.215+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:21:14.213+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T06:21:14.313+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:21:14.294+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T06:21:14.318+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T06:21:14.400+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.243 seconds
[2024-06-26T06:22:33.276+0000] {processor.py:161} INFO - Started process (PID=142) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T06:22:33.286+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T06:22:33.311+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:22:33.309+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T06:22:33.661+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:22:33.626+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T06:22:33.687+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T06:22:33.941+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.716 seconds
[2024-06-26T06:23:25.605+0000] {processor.py:161} INFO - Started process (PID=180) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T06:23:25.611+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T06:23:25.627+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:23:25.626+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T06:23:25.840+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:23:25.798+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T06:23:25.857+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T06:23:26.067+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.527 seconds
[2024-06-26T06:24:28.430+0000] {processor.py:161} INFO - Started process (PID=232) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T06:24:28.439+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T06:24:28.473+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:24:28.472+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T06:24:28.672+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:24:28.593+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T06:24:28.681+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T06:24:28.936+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.524 seconds
[2024-06-26T06:25:21.123+0000] {processor.py:161} INFO - Started process (PID=282) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T06:25:21.129+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T06:25:21.138+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:25:21.137+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T06:25:21.311+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:25:21.272+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T06:25:21.347+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T06:25:21.529+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.435 seconds
[2024-06-26T06:25:52.222+0000] {processor.py:161} INFO - Started process (PID=339) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T06:25:52.231+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T06:25:52.258+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:25:52.257+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T06:25:52.529+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:25:52.464+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T06:25:52.540+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T06:25:52.667+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.482 seconds
[2024-06-26T06:26:23.959+0000] {processor.py:161} INFO - Started process (PID=401) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T06:26:23.963+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T06:26:23.972+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:26:23.970+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T06:26:24.062+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:26:24.042+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T06:26:24.070+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T06:26:24.159+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.226 seconds
[2024-06-26T06:39:47.034+0000] {processor.py:161} INFO - Started process (PID=50) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T06:39:47.043+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T06:39:47.058+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:39:47.053+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T06:39:47.173+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:39:47.146+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T06:39:47.185+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T06:39:47.307+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.321 seconds
[2024-06-26T06:41:08.672+0000] {processor.py:161} INFO - Started process (PID=119) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T06:41:08.676+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T06:41:08.683+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:41:08.682+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T06:41:08.758+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:41:08.743+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T06:41:08.762+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T06:41:08.836+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.183 seconds
[2024-06-26T06:41:39.188+0000] {processor.py:161} INFO - Started process (PID=176) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T06:41:39.189+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T06:41:39.191+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:41:39.191+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T06:41:39.215+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:41:39.211+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T06:41:39.217+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T06:41:39.236+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.054 seconds
[2024-06-26T06:42:09.411+0000] {processor.py:161} INFO - Started process (PID=238) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T06:42:09.412+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T06:42:09.414+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:42:09.413+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T06:42:09.427+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:42:09.424+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T06:42:09.428+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T06:42:09.448+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.042 seconds
[2024-06-26T06:42:40.192+0000] {processor.py:161} INFO - Started process (PID=300) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T06:42:40.193+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T06:42:40.197+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:42:40.196+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T06:42:40.225+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:42:40.218+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T06:42:40.227+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T06:42:40.260+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.078 seconds
[2024-06-26T06:43:12.311+0000] {processor.py:161} INFO - Started process (PID=362) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T06:43:12.315+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T06:43:12.321+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:43:12.320+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T06:43:12.388+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:43:12.374+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T06:43:12.393+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T06:43:12.459+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.169 seconds
[2024-06-26T06:43:42.623+0000] {processor.py:161} INFO - Started process (PID=422) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T06:43:42.624+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T06:43:42.626+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:43:42.626+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T06:43:42.642+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:43:42.639+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T06:43:42.644+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T06:43:42.672+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.056 seconds
[2024-06-26T06:44:13.070+0000] {processor.py:161} INFO - Started process (PID=484) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T06:44:13.076+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T06:44:13.083+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:44:13.082+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T06:44:13.158+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:44:13.142+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T06:44:13.172+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T06:44:13.262+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.227 seconds
[2024-06-26T06:44:44.352+0000] {processor.py:161} INFO - Started process (PID=550) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T06:44:44.357+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T06:44:44.369+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:44:44.364+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T06:44:44.498+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:44:44.475+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T06:44:44.506+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T06:44:44.608+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.291 seconds
[2024-06-26T06:45:39.526+0000] {processor.py:161} INFO - Started process (PID=611) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T06:45:39.533+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T06:45:39.604+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:45:39.603+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T06:45:40.829+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:45:40.746+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T06:45:40.845+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T06:45:41.089+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.643 seconds
[2024-06-26T06:46:16.851+0000] {processor.py:161} INFO - Started process (PID=646) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T06:46:16.955+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T06:46:17.075+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:46:17.073+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T06:46:18.071+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:46:17.931+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T06:46:18.180+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T06:46:18.350+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.571 seconds
[2024-06-26T06:46:55.272+0000] {processor.py:161} INFO - Started process (PID=686) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T06:46:55.278+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T06:46:55.294+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:46:55.292+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T06:46:55.591+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:46:55.547+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T06:46:55.616+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T06:46:55.914+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.710 seconds
[2024-06-26T06:47:35.527+0000] {processor.py:161} INFO - Started process (PID=738) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T06:47:35.540+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T06:47:35.564+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:47:35.563+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T06:47:36.389+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:47:36.138+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T06:47:36.424+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T06:47:36.652+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.191 seconds
[2024-06-26T06:48:08.153+0000] {processor.py:161} INFO - Started process (PID=782) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T06:48:08.179+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T06:48:08.193+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:48:08.191+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T06:48:08.760+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:48:08.700+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T06:48:08.775+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T06:48:08.964+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.855 seconds
[2024-06-26T06:48:39.581+0000] {processor.py:161} INFO - Started process (PID=843) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T06:48:39.582+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T06:48:39.586+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:48:39.585+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T06:48:39.622+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:48:39.616+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T06:48:39.625+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T06:48:39.657+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.085 seconds
[2024-06-26T06:49:09.911+0000] {processor.py:161} INFO - Started process (PID=905) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T06:49:09.913+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T06:49:09.919+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:49:09.918+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T06:49:09.979+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:49:09.967+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T06:49:09.984+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T06:49:10.056+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.159 seconds
[2024-06-26T06:50:07.656+0000] {processor.py:161} INFO - Started process (PID=973) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T06:50:07.678+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T06:50:07.716+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:50:07.714+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T06:50:08.981+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:50:08.811+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T06:50:09.050+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T06:50:09.382+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.762 seconds
[2024-06-26T06:51:24.280+0000] {processor.py:161} INFO - Started process (PID=1040) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T06:51:24.313+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T06:51:24.335+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:51:24.333+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T06:51:24.748+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:51:24.659+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T06:51:24.802+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T06:51:25.073+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.872 seconds
[2024-06-26T06:51:57.501+0000] {processor.py:161} INFO - Started process (PID=1091) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T06:51:57.521+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T06:51:57.561+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:51:57.559+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T06:51:58.099+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:51:57.844+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T06:51:58.129+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T06:51:58.303+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.871 seconds
[2024-06-26T06:52:28.697+0000] {processor.py:161} INFO - Started process (PID=1151) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T06:52:28.698+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T06:52:28.700+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:52:28.700+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T06:52:28.717+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:52:28.714+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T06:52:28.719+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T06:52:28.737+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.044 seconds
[2024-06-26T06:52:59.288+0000] {processor.py:161} INFO - Started process (PID=1213) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T06:52:59.289+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T06:52:59.290+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:52:59.290+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T06:52:59.302+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:52:59.300+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T06:52:59.304+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T06:52:59.321+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.039 seconds
[2024-06-26T06:53:29.922+0000] {processor.py:161} INFO - Started process (PID=1275) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T06:53:29.924+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T06:53:29.927+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:53:29.927+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T06:53:29.955+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:53:29.949+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T06:53:29.959+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T06:53:29.998+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.086 seconds
[2024-06-26T06:54:00.129+0000] {processor.py:161} INFO - Started process (PID=1336) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T06:54:00.132+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T06:54:00.137+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:54:00.137+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T06:54:00.190+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:54:00.179+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T06:54:00.194+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T06:54:00.259+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.150 seconds
[2024-06-26T06:54:32.990+0000] {processor.py:161} INFO - Started process (PID=1383) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T06:54:33.005+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T06:54:33.023+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:54:33.022+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T06:54:33.339+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:54:33.089+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T06:54:33.362+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T06:54:33.622+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.693 seconds
[2024-06-26T06:55:18.034+0000] {processor.py:161} INFO - Started process (PID=1406) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T06:55:18.064+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T06:55:18.070+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:55:18.068+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T06:55:18.290+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:55:18.266+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T06:55:18.310+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T06:55:18.563+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.631 seconds
[2024-06-26T06:56:19.421+0000] {processor.py:161} INFO - Started process (PID=1467) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T06:56:19.425+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T06:56:19.429+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:56:19.428+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T06:56:19.512+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:56:19.497+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T06:56:19.518+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T06:56:19.695+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.320 seconds
[2024-06-26T06:57:10.043+0000] {processor.py:161} INFO - Started process (PID=1534) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T06:57:10.059+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T06:57:10.074+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:57:10.073+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T06:57:10.571+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:57:10.486+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T06:57:10.589+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T06:57:10.763+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.780 seconds
[2024-06-26T06:57:54.202+0000] {processor.py:161} INFO - Started process (PID=1584) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T06:57:54.326+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T06:57:54.363+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:57:54.362+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T06:57:56.059+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:57:55.858+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T06:57:56.115+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T06:57:56.379+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 2.243 seconds
[2024-06-26T06:58:46.913+0000] {processor.py:161} INFO - Started process (PID=1653) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T06:58:46.917+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T06:58:46.921+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:58:46.920+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T06:58:47.012+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:58:46.992+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T06:58:47.018+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T06:58:47.067+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.178 seconds
[2024-06-26T06:59:26.090+0000] {processor.py:161} INFO - Started process (PID=1710) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T06:59:26.097+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T06:59:26.113+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:59:26.111+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T06:59:26.347+0000] {logging_mixin.py:188} INFO - [2024-06-26T06:59:26.328+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T06:59:26.354+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T06:59:26.447+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.398 seconds
[2024-06-26T07:00:02.414+0000] {processor.py:161} INFO - Started process (PID=1766) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T07:00:02.419+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T07:00:02.426+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:00:02.422+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T07:00:02.548+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:00:02.522+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T07:00:02.556+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T07:00:02.667+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.284 seconds
[2024-06-26T07:00:33.635+0000] {processor.py:161} INFO - Started process (PID=1829) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T07:00:33.636+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T07:00:33.637+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:00:33.637+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T07:00:33.655+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:00:33.651+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T07:00:33.657+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T07:00:33.675+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.045 seconds
[2024-06-26T07:01:04.240+0000] {processor.py:161} INFO - Started process (PID=1892) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T07:01:04.241+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T07:01:04.242+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:01:04.242+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T07:01:04.262+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:01:04.258+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T07:01:04.263+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T07:01:04.284+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.049 seconds
[2024-06-26T07:01:35.017+0000] {processor.py:161} INFO - Started process (PID=1955) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T07:01:35.019+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T07:01:35.022+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:01:35.021+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T07:01:35.065+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:01:35.056+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T07:01:35.070+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T07:01:35.117+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.112 seconds
[2024-06-26T07:02:05.836+0000] {processor.py:161} INFO - Started process (PID=2018) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T07:02:05.837+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T07:02:05.837+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:02:05.837+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T07:02:05.850+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:02:05.848+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T07:02:05.852+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T07:02:05.868+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.036 seconds
[2024-06-26T07:02:36.467+0000] {processor.py:161} INFO - Started process (PID=2081) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T07:02:36.468+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T07:02:36.469+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:02:36.469+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T07:02:36.483+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:02:36.480+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T07:02:36.484+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T07:02:36.500+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.037 seconds
[2024-06-26T07:03:06.999+0000] {processor.py:161} INFO - Started process (PID=2144) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T07:03:07.000+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T07:03:07.002+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:03:07.002+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T07:03:07.030+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:03:07.023+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T07:03:07.032+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T07:03:07.059+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.069 seconds
[2024-06-26T07:03:37.619+0000] {processor.py:161} INFO - Started process (PID=2209) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T07:03:37.621+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T07:03:37.623+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:03:37.623+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T07:03:37.655+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:03:37.649+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T07:03:37.657+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T07:03:37.692+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.082 seconds
[2024-06-26T07:04:08.186+0000] {processor.py:161} INFO - Started process (PID=2273) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T07:04:08.187+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T07:04:08.189+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:04:08.188+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T07:04:08.216+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:04:08.211+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T07:04:08.218+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T07:04:08.247+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.069 seconds
[2024-06-26T07:04:39.300+0000] {processor.py:161} INFO - Started process (PID=2337) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T07:04:39.303+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T07:04:39.305+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:04:39.305+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T07:04:39.358+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:04:39.347+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T07:04:39.363+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T07:04:39.735+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.455 seconds
[2024-06-26T07:05:10.208+0000] {processor.py:161} INFO - Started process (PID=2401) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T07:05:10.210+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T07:05:10.211+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:05:10.211+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T07:05:10.232+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:05:10.227+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T07:05:10.234+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T07:05:10.266+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.067 seconds
[2024-06-26T07:05:40.740+0000] {processor.py:161} INFO - Started process (PID=2467) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T07:05:40.741+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T07:05:40.742+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:05:40.742+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T07:05:40.756+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:05:40.753+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T07:05:40.757+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T07:05:40.773+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.037 seconds
[2024-06-26T07:06:11.155+0000] {processor.py:161} INFO - Started process (PID=2529) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T07:06:11.156+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T07:06:11.157+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:06:11.156+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T07:06:11.169+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:06:11.167+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T07:06:11.170+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T07:06:11.186+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.038 seconds
[2024-06-26T07:06:41.800+0000] {processor.py:161} INFO - Started process (PID=2591) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T07:06:41.801+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T07:06:41.802+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:06:41.802+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T07:06:41.815+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:06:41.812+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T07:06:41.816+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T07:06:41.834+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.039 seconds
[2024-06-26T07:07:12.106+0000] {processor.py:161} INFO - Started process (PID=2649) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T07:07:12.110+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T07:07:12.117+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:07:12.116+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T07:07:12.209+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:07:12.190+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T07:07:12.217+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T07:07:12.322+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.243 seconds
[2024-06-26T07:07:45.543+0000] {processor.py:161} INFO - Started process (PID=2718) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T07:07:45.550+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T07:07:45.560+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:07:45.558+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T07:07:45.653+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:07:45.634+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T07:07:45.662+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T07:07:45.762+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.254 seconds
[2024-06-26T07:08:15.975+0000] {processor.py:161} INFO - Started process (PID=2780) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T07:08:15.977+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T07:08:15.979+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:08:15.978+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T07:08:16.007+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:08:16.001+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T07:08:16.010+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T07:08:16.043+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.076 seconds
[2024-06-26T07:08:48.825+0000] {processor.py:161} INFO - Started process (PID=2840) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T07:08:48.830+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T07:08:48.834+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:08:48.833+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T07:08:48.935+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:08:48.912+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T07:08:48.950+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T07:08:49.042+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.256 seconds
[2024-06-26T07:09:21.686+0000] {processor.py:161} INFO - Started process (PID=2894) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T07:09:21.690+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T07:09:21.705+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:09:21.702+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T07:09:22.406+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:09:22.294+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T07:09:22.457+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T07:09:22.896+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.276 seconds
[2024-06-26T07:10:04.620+0000] {processor.py:161} INFO - Started process (PID=2927) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T07:10:04.636+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T07:10:04.651+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:10:04.649+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T07:10:05.459+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:10:04.758+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T07:10:05.472+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T07:10:06.816+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 2.575 seconds
[2024-06-26T07:10:42.508+0000] {processor.py:161} INFO - Started process (PID=2971) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T07:10:42.518+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T07:10:42.542+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:10:42.540+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T07:10:42.834+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:10:42.796+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T07:10:42.850+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T07:10:42.995+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.557 seconds
[2024-06-26T07:11:14.259+0000] {processor.py:161} INFO - Started process (PID=3034) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T07:11:14.321+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T07:11:14.347+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:11:14.345+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T07:11:14.449+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:11:14.435+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T07:11:14.454+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T07:11:14.570+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.356 seconds
[2024-06-26T07:11:49.323+0000] {processor.py:161} INFO - Started process (PID=3093) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T07:11:49.328+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T07:11:49.333+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:11:49.332+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T07:11:49.443+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:11:49.418+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T07:11:49.451+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T07:11:49.539+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.261 seconds
[2024-06-26T07:12:21.986+0000] {processor.py:161} INFO - Started process (PID=3157) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T07:12:22.000+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T07:12:22.005+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:12:22.004+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T07:12:22.536+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:12:22.491+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T07:12:22.546+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T07:12:22.680+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.745 seconds
[2024-06-26T07:13:11.913+0000] {processor.py:161} INFO - Started process (PID=3213) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T07:13:11.948+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T07:13:11.974+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:13:11.972+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T07:13:12.283+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:13:12.239+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T07:13:12.295+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T07:13:12.441+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.594 seconds
[2024-06-26T07:13:42.745+0000] {processor.py:161} INFO - Started process (PID=3274) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T07:13:42.747+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T07:13:42.749+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:13:42.748+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T07:13:42.773+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:13:42.769+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T07:13:42.775+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T07:13:42.799+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.061 seconds
[2024-06-26T07:14:13.106+0000] {processor.py:161} INFO - Started process (PID=3337) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T07:14:13.107+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T07:14:13.108+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:14:13.108+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T07:14:13.130+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:14:13.126+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T07:14:13.132+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T07:14:13.154+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.054 seconds
[2024-06-26T07:14:43.673+0000] {processor.py:161} INFO - Started process (PID=3400) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T07:14:43.675+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T07:14:43.676+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:14:43.676+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T07:14:43.704+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:14:43.699+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T07:14:43.706+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T07:14:43.731+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.065 seconds
[2024-06-26T07:15:18.575+0000] {processor.py:161} INFO - Started process (PID=3463) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T07:15:18.586+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T07:15:18.596+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:15:18.595+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T07:15:19.008+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:15:18.948+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T07:15:19.047+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T07:15:19.285+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.792 seconds
[2024-06-26T07:16:10.533+0000] {processor.py:161} INFO - Started process (PID=3532) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T07:16:10.537+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T07:16:10.557+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:16:10.555+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T07:16:10.883+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:16:10.726+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T07:16:10.907+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T07:16:11.117+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.671 seconds
[2024-06-26T07:39:05.209+0000] {processor.py:161} INFO - Started process (PID=45) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T07:39:05.212+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T07:39:05.221+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:39:05.220+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T07:39:05.307+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:39:05.287+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T07:39:05.312+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T07:39:05.386+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.201 seconds
[2024-06-26T07:39:35.560+0000] {processor.py:161} INFO - Started process (PID=109) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T07:39:35.562+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T07:39:35.568+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:39:35.566+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T07:39:35.619+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:39:35.607+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T07:39:35.624+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T07:39:35.697+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.154 seconds
[2024-06-26T07:40:07.943+0000] {processor.py:161} INFO - Started process (PID=174) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T07:40:07.946+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T07:40:07.976+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:40:07.975+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T07:40:10.425+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:40:09.294+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T07:40:11.115+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T07:40:11.515+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 3.611 seconds
[2024-06-26T07:41:22.107+0000] {processor.py:161} INFO - Started process (PID=240) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T07:41:22.239+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T07:41:22.301+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:41:22.299+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T07:41:23.534+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:41:23.499+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T07:41:23.551+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T07:41:23.784+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.730 seconds
[2024-06-26T07:42:09.446+0000] {processor.py:161} INFO - Started process (PID=282) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T07:42:09.461+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T07:42:09.506+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:42:09.504+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T07:42:10.382+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:42:10.321+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T07:42:10.413+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T07:42:10.706+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.389 seconds
[2024-06-26T07:42:58.221+0000] {processor.py:161} INFO - Started process (PID=327) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T07:42:58.254+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T07:42:58.283+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:42:58.271+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T07:42:58.496+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:42:58.471+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T07:42:58.506+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T07:42:59.263+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.105 seconds
[2024-06-26T07:46:13.466+0000] {processor.py:161} INFO - Started process (PID=388) to work on /opt/airflow/dags/my_dag.py
[2024-06-26T07:46:26.438+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-26T07:46:26.620+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:46:26.441+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-26T07:46:27.193+0000] {logging_mixin.py:188} INFO - [2024-06-26T07:46:26.796+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 30, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
[2024-06-26T07:46:27.219+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-06-26T07:46:28.366+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 15.036 seconds
